name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: 3.2

      - name: Install dependencies
        run: bundle install

      - name: Run linters
        run: bundle exec rubocop

      - name: Run tests
        run: bundle exec rake
